### PR TITLE
Add cross compiling for scala 2.12.1

### PR DESCRIPTION
**Pull request by basert**
This pull request adds scala 2.12.1 support.

### CODE REVIEW

**Comment by JurajBurian** [comment]
Hey @basert thanks. May I ask you for advice ? Do you know how to deploy only 2.12 version to sonatype repos ?

**Comment by basert** [comment]
Sorry, I never published myself, was only going through my dependencies that are not available for 2.12 and added PR's for them.

**Comment by JurajBurian** [comment]
enjoy @basert, pls send me direct mail if you want promote your org as mailer user - in readme

**Comment by basert** [comment]
Hum, did you prepared a new release? I can't find the 2.12 version on maven yet: http://search.maven.org/#search%7Cga%7C1%7Ccom.github.jurajburian

For organization: ESL - https://www.eslgaming.com (we use it for several backend services)

**Comment by JurajBurian** [comment]
It take a some time when fully propagated. 
Try again pls. I can see it . I just published 1.2.1 for scala 2.12 not new release

**Comment by basert** [comment]
Ahh, nice! Can see it as well now. Thanks for your help!

**Pull request merged**
