### PR TITLE
Override updateMessageID to set a custom message id.

### PR DESCRIPTION
**Pull request by basert**
If no message id header is provided the usual behavior is used to generate one.
This is according to the FAQ guidelines: https://javaee.github.io/javamail/FAQ#msgid

### CODE REVIEW

**Comment by JurajBurian** [comment]
Hey @basert  do you want all rights for project releases ? I can also ask for rights for you on Sonatype Nexus, but you must be registered in. Pls let me know if you want it.

**Comment by basert** [comment]
Sure! I signed up at https://issues.sonatype.org, my username is basert. Though a short how-to publish would be awesome :D

**Comment by JurajBurian** [comment]
Just read this: https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html is easy. Also when you deploy to sonatype is necessary to approve deployed artefact.  
Also I created jira on sonatype : https://issues.sonatype.org/browse/OSSRH-38714

**Comment by JurajBurian** [comment]
@basert  fill free to manage whole cycle ... you have a rights to do it :-)

**Comment by basert** [comment]
Woho, successfully published version 1.2.3 to maven :) Thanks for your trust!

**Pull request merged**
